[project]
name = "langflow-app"
version = "0.1.0"
description = ""
authors = [
    {name = "Evan",email = "evan@ivc.media"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "slack-sdk (>=3.35.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
